version: '3'

services:

### Applications Code Container #############################

    # web:
    #   image: debian:jessie
    #   volumes:
    #     - ./www:/var/www

### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./php
      volumes:
        - ../www:/var/www/html
      expose:
        - "9000"
      depends_on:
        - mysql

### PHP-CLI Container #######################################

    php-cli:
      build:
        context: ./php-cli
      volumes:
        - ../www:/var/www/html
      tty: true

### Nginx Server Container ##################################

    nginx:
      build:
        context: ./nginx
      volumes:
          - ../www:/var/www/html
      ports:
          - "8000:80"
          - "443:443"
      depends_on:
          - php-fpm

### MySQL Container #########################################

    mysql:
      image: mysql:5.7
      volumes:
        - mysql-data:/var/lib/mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=123456

### PHPMyAdmin Container #########################################

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8080:80"
      links:
          - mysql:db

### Volumes Setup ###########################################

volumes:
    mysql-data:
